"""The learner's ladder: on the Learn page, and on every chapter of the reader.

The Learning System's five rungs, S0 Explorer to S4 Master, are declared by the
library (program/levels.zknw) and earned by a project that passes its guard,
never by a score. tools/ladder_run.py asked the library which chapters each
rung needs, had each project's guard prove itself on its wrong and right
samples, and asked where a new learner stands. This module turns that run into

  - the ladder on the Learn page (placeholder <!--LADDER-->): each rung, the
    chapters it adds, the project that earns it, what the guard checks, and the
    guard's own verdicts on its samples; then "where you stand", run;
  - a line on every chapter of the reader (reader.html): the rung the chapter
    belongs to and what earns it. The reader is generated by the library; the
    site adds this line to its copy between markers, so a rebuild replaces it
    rather than stacking it. The Arabic and Hausa lines use only the library's
    own text (the project's brief in that language), no translation by the site.

Pedagogy proposed it as "the ladder always visible"; decided
by the author on 2026-10-03.
"""
import json, re, html

def esc(s): return html.escape(str(s), quote=True)
GH = "https://github.com/mayouni/stzlib/blob/main/libraries/stzlib/base/"
NAMES = {"explorer": ("Explorer", "Explorateur"), "builder": ("Builder", "Bâtisseur"), "craftsperson": ("Craftsperson", "Artisan"),
         "architect": ("Architect", "Architecte"), "master": ("Master", "Maître")}

T = {
  "fr": {"intro": "Cinq barreaux, de S0 Explorateur à S4 Maître, déclarés par la bibliothèque. Un barreau est gagné quand chaque exercice de ses chapitres est réussi et que son projet passe son garde, chacun avec une preuve qui correspond encore : un dossier modifié après la réussite ne compte plus. Jamais un score.",
         "chapters": "Chapitres", "through": "chapitres 1 à {n}", "earned": "Gagné par", "checks": "Le garde vérifie",
         "proved": "Le garde s'est éprouvé lui-même : il a refusé {w} dossier(s) faux sur {wt} et accepté {r} juste(s) sur {rt}.",
         "refused": "refusé", "accepted": "accepté", "brief": "la consigne", "guard": "le garde",
         "where_h": "Où vous en êtes",
         "where": "Le site ne voit pas votre dossier : le navigateur n'exécute pas une cellule, et le lecteur le dit. Sur votre poste, la bibliothèque nomme ce qui manque, par son nom. Voici sa réponse pour un apprenant qui commence :",
         "where_note": "Un barreau ne peut pas être écrit à la main dans le fichier de progression : le garde des niveaux le vérifie.",
         "ran": "exécuté le {d} dans la bibliothèque au commit 0e72e2e2c, en {s} s, chaque garde dans son propre processus",
         "out": "Sortie", "levels_guard": "levels_narrated", "kept_note": "Les consignes citées sont celles de la bibliothèque, en français provisoire, en attente de relecture.",
         "strip": "{rung} · {name} · ce chapitre appartient à ce barreau, gagné quand les chapitres 1 à {n} et <bdi>{pid}</bdi> sont réussis : {what}", "strip_link": "L'échelle"},
  "en": {"intro": "Five rungs, from S0 Explorer to S4 Master, declared by the library. A rung is earned when every exercise of its chapters has passed and its project has passed its guard, each with evidence that still matches: a folder changed after the pass no longer counts. Never a score.",
         "chapters": "Chapters", "through": "chapters 1 to {n}", "earned": "Earned by", "checks": "The guard checks",
         "proved": "The guard proved itself: it refused {w} of {wt} wrong folder(s) and accepted {r} of {rt} right one(s).",
         "refused": "refused", "accepted": "accepted", "brief": "the brief", "guard": "the guard",
         "where_h": "Where you stand",
         "where": "The site cannot see your folder: the browser does not run a cell, and the reader says so. On your machine, the library names what is missing, by name. Here is its answer for a learner who is starting:",
         "where_note": "A rung cannot be typed into the progress file by hand: the levels guard checks it.",
         "ran": "run on {d} inside the library at commit 0e72e2e2c, in {s} s, each guard in its own process",
         "out": "Output", "levels_guard": "levels_narrated", "kept_note": "",
         "strip": "{rung} · {name} · this chapter belongs to this rung, earned when chapters 1 to {n} and <bdi>{pid}</bdi> have passed: {what}", "strip_link": "The ladder"},
}

WHERE_CODE = ('oP = StzProgramQ("../../education/program")\noC = oP.CourseQ("elementary-introduction")\n'
              'oL = StzLearnerQ("t_ladder/a-new-learner")\n? oL.HasEarned(oP, oC, "s0")\n? @@( oL.MissingFor(oP, oC, "s0") )')

def load(ROOT):
    f = ROOT / "data" / "ladder-run.json"
    return json.loads(f.read_text(encoding="utf-8")) if f.exists() else None

def inline_code(s):
    """the brief's `code` as <code>, the rest escaped"""
    parts = re.split(r"`([^`]*)`", s)
    return "".join(f"<code>{esc(p)}</code>" if i % 2 else esc(p) for i, p in enumerate(parts))

def rung_of(run):
    """chapter number -> its level record"""
    out = {}
    slugs = {c["slug"]: c["n"] for c in run["chapters"]}
    for lv in run["levels"]:
        for s in lv["chapters"]:
            n = slugs.get(s)
            if n and n not in out: out[n] = lv
    return out

def ladder_html(run, lang):
    t = T[lang]; li = 0 if lang == "en" else 1
    ch = {c["n"]: c for c in run["chapters"]}
    rows, prev = [], 0
    for lv in run["levels"]:
        n = len(lv["chapters"])
        new = [ch[i] for i in range(prev + 1, n + 1) if i in ch]
        prev = n
        p = run["projects"][lv["earned-by"]]
        b = p["brief"].get(lang) or p["brief"]["en"]
        chap = " · ".join(f'<a href="../reader.html#{lang}:{c["n"]}">{c["n"]} {esc(c.get(lang, c["en"]))}</a>' for c in new)
        refusals = []
        for s in p["samples"]:
            if not s["passed"]:
                said = s["why"].split("It said: ", 1)[-1] if "It said: " in s["why"] else s["why"]
                refusals.append(f'<span class="mono">{esc(s["name"])}</span> <b class="g-other">{t["refused"]}</b> : {esc(said)}'.replace(" : ", ": " if lang == "en" else " : "))
            else:
                refusals.append(f'<span class="mono">{esc(s["name"])}</span> <b class="g-same">{t["accepted"]}</b>')
        rows.append(f'''<div class="rung">
  <div class="rung-id"><b>{esc(lv["id"].upper())}</b><span>{esc(NAMES[lv["named"]][li])}</span></div>
  <div class="rung-body">
    <p><b>{t["chapters"]}</b> : {chap}</p>
    <p><b>{t["earned"]}</b> <span class="mono">{esc(lv["earned-by"])}</span> : {inline_code(b["what"])}</p>
    <p><b>{t["checks"]}</b>{":" if lang == "en" else " :"}</p><ul>{"".join(f"<li>{inline_code(c)}</li>" for c in b["checks"])}</ul>
    <p class="proof">{t["proved"].format(w=p.get("wrong_refused", 0), wt=p.get("wrong", 0), r=p.get("right_accepted", 0), rt=p.get("right", 0))}</p>
    <ul class="rung-samples">{"".join(f"<li>{x}</li>" for x in refusals)}</ul>
    <p class="proof"><a href="{GH}education/program/projects/{esc(lv["earned-by"])}/brief.{lang}.md">{t["brief"]}</a> · <a href="{GH}education/program/projects/{esc(lv["earned-by"])}/guard.ring">{t["guard"]}</a> · <a href="{GH}education/program/projects/{esc(lv["earned-by"])}">wrong/ · right/</a></p>
  </div>
</div>'''.replace("</b> : ", "</b>: " if lang == "en" else "</b> : ").replace("</span> : ", "</span>: " if lang == "en" else "</span> : "))
    nl = run["new_learner"]
    where = (f'<h3>{t["where_h"]}</h3><p>{t["where"]}</p>'
             f'<div class="run"><div><div class="lbl">Softanza</div><pre>{esc(WHERE_CODE)}</pre></div>'
             f'<div class="out"><div class="lbl">{t["out"]}</div><pre>{1 if nl["earned_s0"] else 0}\n{esc(nl["missing_s0"])}</pre></div></div>'
             f'<p class="ran">{t["ran"].format(d=esc(run["ran"]), s=run["seconds"])} · <a href="{GH}education/stzLearner.ring">stzLearner.ring</a> · <a href="{GH}education/stzProject.ring">stzProject.ring</a></p>'
             f'<p class="proof">{t["where_note"]} <a href="{GH}test/education/levels_narrated.ring">{t["levels_guard"]}</a></p>')
    note = f'<p class="proof">{t["kept_note"]}</p>' if t["kept_note"] else ""
    return f'<p>{t["intro"]}</p><div class="ladder">{"".join(rows)}</div>{note}{where}'

STRIP_CSS = ("<style>/*stz-ladder*/.stz-ladder{border:1px solid var(--line);border-inline-start:4px solid var(--accent);background:var(--panel);"
             "padding:8px 14px;border-radius:8px;margin:4px 0 16px;color:var(--ink)}.stz-ladder b,.stz-ladder a{color:var(--accent)}"
             ".stz-ladder bdi{white-space:nowrap;font-family:ui-monospace,Consolas,monospace}</style>")

def inject_reader(text, run):
    """the rung of each chapter, under its title, in each of the four languages"""
    text = re.sub(r"<!--stz-ladder-->.*?<!--/stz-ladder-->", "", text, flags=re.S)
    text = re.sub(r"<style>/\*stz-ladder\*/.*?</style>", "", text, flags=re.S)       # by marker, so an edited style never stacks
    text = text.replace("</head>", STRIP_CSS + "</head>", 1)
    rungs = rung_of(run)
    def strip(lang, n):
        lv = rungs.get(n)
        if not lv: return ""
        p = run["projects"][lv["earned-by"]]
        b = p["brief"].get(lang) or p["brief"]["en"]
        upto = len(lv["chapters"])
        if lang in ("en", "fr"):
            t = T[lang]
            body = t["strip"].format(rung=esc(lv["id"].upper()), name=esc(NAMES[lv["named"]][0 if lang == "en" else 1]),
                                     n=upto, pid=esc(lv["earned-by"]), what=inline_code(b["what"]))
            link = f' <a href="{lang}/learn.html#ladder">{t["strip_link"]}</a>'
        else:
            # Arabic and Hausa: only the library's own words, the brief in that language
            body = f'{esc(lv["id"].upper())} · 1 – {upto} · <bdi>{esc(lv["earned-by"])}</bdi> · {inline_code(b["what"])}'
            link = ' <a href="en/learn.html#ladder">S0 – S4</a>'
        return f'<!--stz-ladder--><p class="stz-ladder"><b>{body.split(" · ", 1)[0]}</b> · {body.split(" · ", 1)[1]}{link}</p><!--/stz-ladder-->'
    out, pos = [], 0
    for m in re.finditer(r'<article id="(en|fr|ar|ha)-(\d+)"[^>]*>', text):
        lang, n = m.group(1), int(m.group(2))
        h = text.find("</h1>", m.end())
        if h < 0: continue
        out.append(text[pos:h + 5]); out.append(strip(lang, n)); pos = h + 5
    out.append(text[pos:])
    return "".join(out)
